apiVersion: batch/v1
kind: CronJob
metadata:
  name: transmission-rss
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: transmission-rss
              image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
              args: ["-c", "/app/config.toml"]
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: config-cm
                  mountPath: /app
                - mountPath: "/db"
                  name: persistence
          volumes:
            - name: config-cm
              configMap:
                name: {{ .Values.configMapName }}
            - name: persistence
              persistentVolumeClaim:
                claimName: transmission-rss