apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-rss
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/storage/data/transmission-rss"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-rss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi